Add validation of node profile before executing command

diff --git a/bin/generate-participation-key b/bin/generate-participation-key
--- a/bin/generate-participation-key
+++ b/bin/generate-participation-key
@@ -1,14 +1,56 @@
 #!/bin/bash
+
 echo ""
 echo "Tip:"
 echo "    To get the latest updates, including updating participation key if needed, rerun the installer."
 echo "    If your current participation key expires within ~14 days the installer will automatically offer to generate a new key."
 echo "    To rerun the installer execute:"
+# shellcheck disable=SC2016
 echo '      /bin/bash -c "$(curl -fsSL https://get.voi.network/swarm)"'
 echo ""
 
-container_id=$(docker ps -q -f name=voinetwork_algod)
-if [ -z "${container_id}" ]; then
+VOINETWORK_PROFILE=""
+CONTAINER_ID=""
+
+function abort() {
+  echo "$1"
+  exit 1
+}
+
+function get_profile() {
+    local voi_home="${HOME}/voi"
+    if [ -f "${voi_home}/profile" ]; then
+      VOINETWORK_PROFILE=$(cat "${voi_home}/profile")
+    else
+      abort "Profile not found. Exiting the program."
+    fi
+
+    if [ -z "${VOINETWORK_PROFILE}" ]; then
+      abort "Profile not found. Exiting the program."
+    fi
+}
+
+function get_container_id() {
+  if [[ ${VOINETWORK_PROFILE} == "relay" ]]; then
+    CONTAINER_ID=$(docker ps -q -f name=voinetwork_relay)
+  elif [[ ${VOINETWORK_PROFILE} == "participation" ]]; then
+    CONTAINER_ID=$(docker ps -q -f name=voinetwork_algod)
+  else
+    abort "Invalid profile. Exiting the program."
+  fi
+}
+
+function validate_supported_node_type() {
+  if [[ ${VOINETWORK_PROFILE} != "participation" ]]; then
+    abort "This operation is only supported for participation nodes. Exiting the program."
+  fi
+}
+
+get_profile
+get_container_id
+validate_supported_node_type
+
+if [ -z "${CONTAINER_ID}" ]; then
     echo "AVM container is not running. Please start it first."
     exit 1
 fi
@@ -19,4 +61,4 @@ if [ -z "$1" ]; then
     exit 1
 fi
 
-docker exec -e account_addr="$1" -it "${container_id}" bash -c 'start=$(goal node status | grep "Last committed block:" | cut -d\  -f4) && duration=${duration:-2000000} && end=$((start + duration)) && goal account addpartkey -a ${account_addr} --roundFirstValid $start --roundLastValid $end'
+docker exec -e account_addr="$1" -it "${CONTAINER_ID}" bash -c 'start=$(goal node status | grep "Last committed block:" | cut -d\  -f4) && duration=${duration:-2000000} && end=$((start + duration)) && goal account addpartkey -a ${account_addr} --roundFirstValid $start --roundLastValid $end'
diff --git a/bin/get-node-status b/bin/get-node-status
--- a/bin/get-node-status
+++ b/bin/get-node-status
@@ -1,5 +1,46 @@
 #!/bin/bash
 
+VOINETWORK_PROFILE=""
+CONTAINER_ID=""
+
+function abort() {
+  echo "$1"
+  exit 1
+}
+
+function get_profile() {
+    local voi_home="${HOME}/voi"
+    if [ -f "${voi_home}/profile" ]; then
+      VOINETWORK_PROFILE=$(cat "${voi_home}/profile")
+    else
+      abort "Profile not found. Exiting the program."
+    fi
+
+    if [ -z "${VOINETWORK_PROFILE}" ]; then
+      abort "Profile not found. Exiting the program."
+    fi
+}
+
+function get_CONTAINER_ID() {
+  if [[ ${VOINETWORK_PROFILE} == "relay" ]]; then
+    CONTAINER_ID=$(docker ps -q -f name=voinetwork_relay)
+  elif [[ ${VOINETWORK_PROFILE} == "participation" ]]; then
+    CONTAINER_ID=$(docker ps -q -f name=voinetwork_algod)
+  else
+    abort "Invalid profile. Exiting the program."
+  fi
+}
+
+function validate_supported_node_type() {
+  if [[ ${VOINETWORK_PROFILE} != "participation" ]]; then
+    abort "This operation is only supported for participation nodes. Exiting the program."
+  fi
+}
+
+get_profile
+get_CONTAINER_ID
+validate_supported_node_type
+
 is_root=0
 
 execute_sudo() {
@@ -15,7 +56,7 @@ get_algod_token() {
 }
 
 get_last_committed_block() {
-  docker exec -it "${container_id}" bash -c "goal node status | grep 'Last committed block' | cut -d' ' -f4 | tr -cd '[:digit:]'"
+  docker exec -it "${CONTAINER_ID}" bash -c "goal node status | grep 'Last committed block' | cut -d' ' -f4 | tr -cd '[:digit:]'"
 }
 
 get_accounts() {
@@ -62,7 +103,7 @@ get_participation_expiration_eta() {
 display_account_information() {
   local account_address=$1
   local account_details
-  account_details=$(docker exec -it "${container_id}" bash -c "curl -X GET -H 'Content-Type: application/json' -H 'X-Algo-API-Token: ${algod_token}' http://localhost:8080/v2/accounts/${account_address}")
+  account_details=$(docker exec -it "${CONTAINER_ID}" bash -c "curl -X GET -H 'Content-Type: application/json' -H 'X-Algo-API-Token: ${algod_token}' http://localhost:8080/v2/accounts/${account_address}")
 
   echo "Address: ${account_address}"
   echo "Balance: $(echo "${account_details}" | jq -r '.amount') microVoi"
@@ -74,8 +115,8 @@ display_account_information() {
 
   ## This is a workaround to get the last valid round of the active participation key that is installed on the system.
   ## If using REST API we will get key for last online transaction, which is valid for other usecases
-  #active_key_last_valid_round=$(docker exec -it "${container_id}" bash -c 'goal account listpartkeys' | awk '$1=="yes" {print $6}' | tr -cd '[:digit:]')
-  active_key_last_valid_round=$(docker exec -it "${container_id}" bash -c 'goal account listpartkeys' | awk -v addr="${account_address}" '$1=="yes" && substr($2, 1, 4) == substr(addr, 1, 4) && substr($2, length($2)-3) == substr(addr, length(addr)-3) {print $6}' | tr -cd '[:digit:]')
+  #active_key_last_valid_round=$(docker exec -it "${CONTAINER_ID}" bash -c 'goal account listpartkeys' | awk '$1=="yes" {print $6}' | tr -cd '[:digit:]')
+  active_key_last_valid_round=$(docker exec -it "${CONTAINER_ID}" bash -c 'goal account listpartkeys' | awk -v addr="${account_address}" '$1=="yes" && substr($2, 1, 4) == substr(addr, 1, 4) && substr($2, length($2)-3) == substr(addr, length(addr)-3) {print $6}' | tr -cd '[:digit:]')
 
   if [[ -z "${active_key_last_valid_round}" ]]; then
     echo "Participation status: No active participation key found."
@@ -84,13 +125,12 @@ display_account_information() {
 
   existing_expiration_date=$(get_participation_expiration_eta "${active_key_last_valid_round}" "${last_committed_block}")
 
-  echo "Participation status: $(docker exec -it "${container_id}" bash -c 'goal account dump -a '"${account_address}"' | jq -r '\''if (.onl == 1) then "online" else "offline" end'\''')"
+  echo "Participation status: $(docker exec -it "${CONTAINER_ID}" bash -c 'goal account dump -a '"${account_address}"' | jq -r '\''if (.onl == 1) then "online" else "offline" end'\''')"
   echo "Participation key expires at block: ${active_key_last_valid_round} (last committed: ${last_committed_block})"
   echo "Participation key expected to expire at: ${existing_expiration_date}"
 }
 
-container_id=$(docker ps -q -f name=voinetwork_algod)
-if [ -z "${container_id}" ]; then
+if [ -z "${CONTAINER_ID}" ]; then
     echo "AVM container is not running. Please start it first."
     exit 1
 fi
@@ -106,19 +146,19 @@ fi
 
 declare -A health_checks
 
-if [[ $(docker exec -it "${container_id}" bash -c "goal node status") ]]; then
+if [[ $(docker exec -it "${CONTAINER_ID}" bash -c "goal node status") ]]; then
     health_checks["Daemon running"]="true"
 else
     health_checks["Daemon running"]="false"
 fi
 
-if [[ $(docker exec "${container_id}" bash -c "curl -fs http://localhost:8080/health") ]]; then
+if [[ $(docker exec "${CONTAINER_ID}" bash -c "curl -fs http://localhost:8080/health") ]]; then
     health_checks["Daemon healthy"]="true"
 else
     health_checks["Daemon healthy"]="false"
 fi
 
-if [[ $(docker exec "${container_id}" bash -c "curl -fs http://localhost:8080/ready") ]]; then
+if [[ $(docker exec "${CONTAINER_ID}" bash -c "curl -fs http://localhost:8080/ready") ]]; then
     health_checks["Daemon ready (and caught up)"]="true"
 else
     health_checks["Daemon ready (and caught up)"]="false"
@@ -128,7 +168,7 @@ get_algod_token
 
 echo "Voi Swarm Docker status:"
 echo "**************"
-swarm_running_image=$(docker inspect --format='{{.Image}}' "${container_id}" | cut -d':' -f2)
+swarm_running_image=$(docker inspect --format='{{.Image}}' "${CONTAINER_ID}" | cut -d':' -f2)
 echo "Running container image (sha256): ${swarm_running_image}"
 echo "Auto-update enabled: $(awk -F'=' '/swarm.cronjob.enable=/ {print $2}' "${HOME}"/voi/docker/compose.yml)"
 echo "Auto-update schedule (cron format): $(awk -F'=' '/swarm.cronjob.schedule=/ {print $2}' "${HOME}"/voi/docker/compose.yml)"
@@ -136,7 +176,7 @@ echo ""
 
 echo "AVM version:"
 echo "**************"
-algod_version=$(docker exec -it "${container_id}" bash -c 'goal version -v')
+algod_version=$(docker exec -it "${CONTAINER_ID}" bash -c 'goal version -v')
 echo "${algod_version}"
 echo ""
 
diff --git a/bin/notification-test b/bin/notification-test
--- a/bin/notification-test
+++ b/bin/notification-test
@@ -1,12 +1,46 @@
 #!/bin/bash
 
-container_id=$(docker ps -q -f name=voinetwork_notify)
-if [ -z "${container_id}" ]; then
+VOINETWORK_PROFILE=""
+CONTAINER_ID=""
+
+function abort() {
+  echo "$1"
+  exit 1
+}
+
+function get_profile() {
+    local voi_home="${HOME}/voi"
+    if [ -f "${voi_home}/profile" ]; then
+      VOINETWORK_PROFILE=$(cat "${voi_home}/profile")
+    else
+      abort "Profile not found. Exiting the program."
+    fi
+
+    if [ -z "${VOINETWORK_PROFILE}" ]; then
+      abort "Profile not found. Exiting the program."
+    fi
+}
+
+function get_container_id() {
+  CONTAINER_ID=$(docker ps -q -f name=voinetwork_algod)
+}
+
+function validate_supported_node_type() {
+  if [[ ${VOINETWORK_PROFILE} != "participation" ]]; then
+    abort "This operation is only supported for participation nodes. Exiting the program."
+  fi
+}
+
+get_profile
+get_container_id
+validate_supported_node_type
+
+if [ -z "${CONTAINER_ID}" ]; then
     echo "notification container is not running. Please start it first."
     exit 1
 fi
 
 echo "Sending notification"
-docker exec -it "${container_id}" bash -c "curl -sS -X POST --data '{\"title\": \"Voi Participation Key Notification Test\", \"body\": \"Notification test for Voi Network\"}' localhost:5000 >> /dev/null && echo \"Notification sent\""
+docker exec -it "${CONTAINER_ID}" bash -c "curl -sS -X POST --data '{\"title\": \"Voi Participation Key Notification Test\", \"body\": \"Notification test for Voi Network\"}' localhost:5000 >> /dev/null && echo \"Notification sent\""
 
 echo "Note: After making changes to your notification.yml settings file, make sure to rerun the install script."
diff --git a/bin/set-autoupdate b/bin/set-autoupdate
--- a/bin/set-autoupdate
+++ b/bin/set-autoupdate
@@ -1,5 +1,34 @@
 #!/bin/bash
 
+VOINETWORK_PROFILE=""
+
+function abort() {
+  echo "$1"
+  exit 1
+}
+
+function get_profile() {
+    local voi_home="${HOME}/voi"
+    if [ -f "${voi_home}/profile" ]; then
+      VOINETWORK_PROFILE=$(cat "${voi_home}/profile")
+    else
+      abort "Profile not found. Exiting the program."
+    fi
+
+    if [ -z "${VOINETWORK_PROFILE}" ]; then
+      abort "Profile not found. Exiting the program."
+    fi
+}
+
+function validate_supported_node_type() {
+  if [[ ${VOINETWORK_PROFILE} != "participation" && ${VOINETWORK_PROFILE} != "relay" ]]; then
+    abort "This operation is only supported for participation and relay nodes. Exiting the program."
+  fi
+}
+
+get_profile
+validate_supported_node_type
+
 echo "Enable/Disable autoupdate for your node"
 echo ""
 echo "To enable autoupdate use: set-autoupdate true"
@@ -15,8 +44,6 @@ if [[ $1 != "true" && $1 != "false" ]]; then
   echo "Invalid value for autoupdate. Please use 'true' or 'false'."
   exit 1
 fi
-
-VOINETWORK_PROFILE=$(cat "${HOME}/voi/profile")
 
 if [[ ${VOINETWORK_PROFILE} == "relay" ]]; then
   docker_filename="${HOME}/voi/docker/relay.yml"
diff --git a/bin/set-relay-name b/bin/set-relay-name
--- a/bin/set-relay-name
+++ b/bin/set-relay-name
@@ -1,5 +1,34 @@
 #!/bin/bash
 
+VOINETWORK_PROFILE=""
+
+function abort() {
+  echo "$1"
+  exit 1
+}
+
+function get_profile() {
+    local voi_home="${HOME}/voi"
+    if [ -f "${voi_home}/profile" ]; then
+      VOINETWORK_PROFILE=$(cat "${voi_home}/profile")
+    else
+      abort "Profile not found. Exiting the program."
+    fi
+
+    if [ -z "${VOINETWORK_PROFILE}" ]; then
+      abort "Profile not found. Exiting the program."
+    fi
+}
+
+function validate_supported_node_type() {
+  if [[ ${VOINETWORK_PROFILE} != "relay" ]]; then
+    abort "This operation is only supported for relay nodes. Exiting the program."
+  fi
+}
+
+get_profile
+validate_supported_node_type
+
 set_relay_name() {
     echo "If you are operating a relay node you need to set a relay name in accordance with the naming convention."
     echo "The relay name should be in the format: <your initials>-<provider-code>-<iso-3166-alpha2-country-code>-<supported-iata-airport-code>-<your-chosen-identifier>"
diff --git a/bin/set-telemetry-name b/bin/set-telemetry-name
--- a/bin/set-telemetry-name
+++ b/bin/set-telemetry-name
@@ -1,4 +1,46 @@
 #!/bin/bash
+
+VOINETWORK_PROFILE=""
+CONTAINER_ID=""
+
+function abort() {
+  echo "$1"
+  exit 1
+}
+
+function get_profile() {
+    local voi_home="${HOME}/voi"
+    if [ -f "${voi_home}/profile" ]; then
+      VOINETWORK_PROFILE=$(cat "${voi_home}/profile")
+    else
+      abort "Profile not found. Exiting the program."
+    fi
+
+    if [ -z "${VOINETWORK_PROFILE}" ]; then
+      abort "Profile not found. Exiting the program."
+    fi
+}
+
+function get_container_id() {
+  if [[ ${VOINETWORK_PROFILE} == "relay" ]]; then
+    CONTAINER_ID=$(docker ps -q -f name=voinetwork_relay)
+  elif [[ ${VOINETWORK_PROFILE} == "participation" ]]; then
+    CONTAINER_ID=$(docker ps -q -f name=voinetwork_algod)
+  else
+    abort "Invalid profile. Exiting the program."
+  fi
+}
+
+function validate_supported_node_type() {
+  if [[ ${VOINETWORK_PROFILE} != "participation" ]]; then
+    abort "This operation is only supported for participation nodes. Exiting the program."
+  fi
+}
+
+get_profile
+get_container_id
+validate_supported_node_type
+
 is_root=0
 
 execute_sudo() {
@@ -55,8 +97,7 @@ update_guid_in_config() {
   echo "${logging_config}" | jq --arg guid "${guid}" '.GUID = $guid'
 }
 
-container_id=$(docker ps -q -f name=voinetwork_algod)
-if [ -z "${container_id}" ]; then
+if [ -z "${CONTAINER_ID}" ]; then
     echo "AVM container is not running. Please start it first."
     exit 1
 fi
